### PR TITLE
Update solution.txt

### PR DESCRIPTION
**Pull request by RamonZhou**
A typo

### CODE REVIEW

**Review by ghost — CHANGES_REQUESTED** [review]
just a typo why change so much?

**Comment by RamonZhou** [comment]
dunno... I have just changed **one** character.

**Comment by ghost** [comment]
But it shows that you added 42 lines and deleted 42 lines

**Comment by RamonZhou** [comment]
Yes I'm also confused.

**Comment by ghost** [comment]
Maybe it's the problem of charset

**Comment by ghost** [comment]
please use UTF-8

**Comment by RamonZhou** [comment]
it said

> We've detected the file encoding as **GB18030**. When you commit changes we will transcode it to **UTF-8**.

So it was GB18030 before and UTF-8 now.

**Pull request merged**
